DELETE FROM chart_of_accounts WHERE chart='FY_Detail_Summary'
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 500, 'Sales, UK', 'Income');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 600, 'Purchases', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 610, 'Sub Contract Cost', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 700, 'Establishment costs', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 750, 'Directors Remuneration', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 760, 'Staff training', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 770, 'Office Equipment Depreciation', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 800, 'Sundry Expenses', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 810, 'Telephone and fax', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 815, 'Office expenses', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 820, 'Computer software and maintenance costs', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 825, 'Printing, postage and stationery', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 830, 'Accountancy Fees', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 835, 'Legal and professional fees', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 840, 'Travel and subsistence', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 890, 'Bank charges', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 910, 'Tax on(loss)/profit on ordinary acitivies', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 920, 'Dividends', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 100, 'Tangible fixed assets', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 110, 'Debtors', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 102, 'Office Equipment Cost', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 103, 'Office Equipment Depreciation', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 120, 'Cash at bank and in hand', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 200, 'Creditors: Amounts falling due within one year', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 210, 'Creditors: Amounts falling due after more than one year', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 300, 'Profit and Loss Account', 'Equity');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('FY_Detail_Summary', 310, 'Called up share capital', 'Equity');
