DELETE FROM chart_of_accounts WHERE chart='SAGE'
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8435, 'Admin Travel', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8414, 'Repairs/Maint/Bldgs', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8410, 'Admin Rent & Rates', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7906, 'Exchange Rate Variance', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7206, 'Factory Salaries', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7204, 'Factory Rent & Rates', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 5000, 'Materials Cost', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8400, 'Admin Gas & Electricity', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8200, 'Audit Fees', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7102, 'Packaging', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8426, 'Telephone', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 4905, 'Carriage', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8408, 'Postage', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7200, 'Factory Depreciation', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7000, 'Factory Wages', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 4000, 'Sales', 'Income');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8405, 'Motor Running', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8420, 'Admin Salaries', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7100, 'Factory Gas & Elec', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8433, 'New Product Development', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8440, 'Admin Sundries', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 5001, 'Material Cost Adjustment', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 6201, 'Advertising', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8201, 'Legal/Professional', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7105, 'Works Sundries', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 6200, 'Sales Manager', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8430, 'Computer/EDI/Internet', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7103, 'Machine Repairs', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7202, 'Factory Insurance', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 4009, 'Discounts Allowed', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8402, 'Admin Insurance', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8204, 'Bank Charges/Interest', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7006, 'Redundancy Costs', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7020, 'Delapidations Provision', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 6100, 'Commissions', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8424, 'Stationary', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8310, 'Gain/Loss on Disposal of Assets', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8300, 'Admin Depreciation', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8100, 'Bad Debts', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1102, 'I. N. Rankin Sales Ltd', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2106, 'Corporation Tax', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1103, 'Directors Loan A/C', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1100, 'Debtors Control Account', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1202, 'Bank Current USD', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1115, 'The Bedding Specialist', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1204, 'Petty Cash', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1200, 'Bank Current Account', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2100, 'Creditors Control Account', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2125, 'Profit & Loss Prior Years', 'Equity');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2108, 'VAT', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2103, 'I. N. Rankin Oil Ltd', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 10, 'Fixed Assets', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2107, 'PAYE & NI', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2105, 'Notional Tax on Directors Loan', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2126, 'Profit & Loss Current Year', 'Equity');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1001, 'Stock', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2120, 'Share Capital', 'Equity');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1203, 'Bank Euro A/c', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2104, 'Gavin Rankin/ D W Trustees', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2109, 'Accruals & Prepayments', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2110, 'Accumulated Depreciation Provision', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 20, 'Fixed Assets 1', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 21, 'Fixed Assets 1 Depreciation', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 30, 'Fixed Assets 2', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 31, 'Fixed Assets 2 Depreciation', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 40, 'Fixed Assets 3', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 41, 'Fixed Assets 3 Depreciation', 'Asset');
