DELETE FROM chart_of_accounts WHERE chart='SAGE';
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8435, 'Admin Travel', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8414, 'Repairs/Maint/Bldgs', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8410, 'Admin Rent & Rates', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7906, 'Exchange Rate Variance', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7206, 'Factory Salaries', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7204, 'Factory Rent & Rates', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 5000, 'Materials Cost', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8400, 'Admin Gas & Electricity', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8200, 'Audit Fees', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7102, 'Packaging', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8426, 'Telephone', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 4905, 'Carriage', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8408, 'Postage', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7200, 'Factory Depreciation', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7000, 'Factory Wages', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 4000, 'Sales', 'Income');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8405, 'Motor Running', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8420, 'Admin Salaries', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7100, 'Factory Gas & Elec', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8433, 'New Product Development', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8440, 'Admin Sundries', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 5001, 'Material Cost Adjustment', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 6201, 'Advertising', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8201, 'Legal/Professional', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7105, 'Works Sundries', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 6200, 'Sales Manager', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8430, 'Computer/EDI/Internet', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7103, 'Machine Repairs', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7202, 'Factory Insurance', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 4009, 'Discounts Allowed', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8402, 'Admin Insurance', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8204, 'Bank Charges/Interest', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7006, 'Redundancy Costs', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7020, 'Delapidations Provision', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 6100, 'Commissions', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8424, 'Stationary', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8310, 'Gain/Loss on Disposal of Assets', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8300, 'Admin Depreciation', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8100, 'Bad Debts', 'Expense');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1102, 'I. N. Rankin Sales Ltd', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2106, 'Corporation Tax', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1103, 'Directors Loan A/C', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1100, 'Debtors Control Account', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1202, 'Bank Current USD', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1115, 'The Bedding Specialist', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1204, 'Petty Cash', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1200, 'Bank Current Account', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2100, 'Creditors Control Account', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2125, 'Profit & Loss Prior Years', 'Equity');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2103, 'I. N. Rankin Oil Ltd', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 10, 'Fixed Assets', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2107, 'PAYE & NI', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2105, 'Notional Tax on Directors Loan', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2126, 'Profit & Loss Current Year', 'Equity');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1001, 'Stock', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2120, 'Share Capital', 'Equity');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1203, 'Bank Euro A/c', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2104, 'Gavin Rankin/ D W Trustees', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2108, 'Accumulated Depreciation Provision', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2109, 'Accruals & Prepayments', 'Liability');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2110, 'Prepayments', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2111, 'Motor Prepayments', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2112, 'Prepayments', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 20, 'Fixed Assets 1', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 21, 'Fixed Assets 1 Depreciation', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 30, 'Fixed Assets 2', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 31, 'Fixed Assets 2 Depreciation', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 40, 'Fixed Assets 3', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 41, 'Fixed Assets 3 Depreciation', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 9999, 'Suspense Account', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 9998, 'Suspense Account USD', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2320, 'Unknown 1', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2101, 'Unknown 2', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2102, 'Unknown 3', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7503, 'Unknown 4', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1104, 'Unknown 5', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1101, 'Unknown 6', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1110, 'Unknown 7', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1117, 'Unknown 8', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1120, 'Unknown 9', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8301, 'Unknown 10', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 3200, 'Unknown 11', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 3210, 'Unknown 12', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2200, 'Unknown 22', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2201, 'Unknown 23', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2202, 'Unknown 24', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2204, 'Unknown 25', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2210, 'Unknown 26', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2211, 'Unknown 27', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8102, 'Unknown 28', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 2220, 'Unknown 58', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 4200, 'Unknown 59', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7604, 'Unknown 30', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1205, 'Unknown 40', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1207, 'Unknown 41', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 3000, 'Unknown 42', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1210, 'Unknown 43', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1212, 'Unknown 44', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1220, 'Unknown 45', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1230, 'Unknown 46', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1240, 'Unknown 47', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 7901, 'Unknown 48', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1250, 'Unknown 49', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1232, 'Unknown 50', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1252, 'Unknown 51', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 8421, 'Unknown 52', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1254, 'Unknown 53', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1256, 'Unknown 54', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1260, 'Unknown 55', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1004, 'Unknown 56', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1262, 'Unknown 57', 'Asset');
INSERT INTO chart_of_accounts (chart, code, name, category) VALUES ('SAGE', 1263, 'Unknown 58', 'Asset');
